# Default values for simple-prima-nota
global:
  imageRegistry: "docker.io"

pgadmin:
  enabled: true
  image:
    registry: docker.io
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent
  auth:
    email: admin@prima-nota.com
    password: ""
  env:
    PGADMIN_DEFAULT_EMAIL: admin@prima-nota.com
    PGADMIN_DEFAULT_PASSWORD: ""
    PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    PGADMIN_CONFIG_LOGIN_BANNER: "Prima Nota - Database Management"
    PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "20"
    PGADMIN_LISTEN_PORT: "5050"
    PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT: "None"
    PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE: "False"
  service:
    type: ClusterIP
    port: 5050
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  auth:
    database: prima_nota
    username: postgres
    password: ""
  persistence:
    enabled: true
    size: 8Gi
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 5432

backend:
  enabled: true
  image:
    registry: docker.io
    repository: vcnngr/pnbackend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  env:
    NODE_ENV: production
    PORT: 3001
    JWT_SECRET: ""
    RATE_LIMIT_WINDOW_MS: 900000
    RATE_LIMIT_MAX_REQUESTS: 100
    MAX_FILE_SIZE: 10485760
    LOG_LEVEL: info
  defaultUser:
    enabled: true
    username: admin
    email: admin@prima-nota.com
    password: ""
    firstName: Admin
    lastName: User
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /api/health
      port: 3001
    initialDelaySeconds: 50
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3001
    initialDelaySeconds: 30
    periodSeconds: 15

frontend:
  enabled: true
  image:
    registry: docker.io
    repository: vcnngr/pnfrontend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    REACT_APP_API_URL: /api
    REACT_APP_NAME: Prima Nota
    REACT_APP_VERSION: 1.0.0
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: le-global-issuer
  hosts:
    - host: prima-nota.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /pgadmin
          pathType: Prefix
          service: pgadmin
  tls:
    - secretName: example-tls
      hosts:
        - prima-nota.example.com

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
