# Default values for simple-prima-nota
global:
  imageRegistry: "docker.io"

# PostgreSQL Standalone (modalità attuale)
postgresql:
  enabled: false  # Disabilitato di default per favorire CloudNativePG
  image:
    registry: docker.io
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  auth:
    database: prima_nota
    username: postgres
    password: ""
  persistence:
    enabled: true
    size: 8Gi
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 5432

# CloudNativePG Cluster (modalità enterprise)
cloudnativepg:
  enabled: true  # Abilitato di default
  cluster:
    name: "prima-nota-postgres"  # Nome del cluster
    instances: 3
    primaryUpdateStrategy: unsupervised
    
    # Immagine PostgreSQL
    imageName: ghcr.io/cloudnative-pg/postgresql:16.1

    # === SUPERUSER ACCESS ===
    enableSuperuserAccess: true  # Abilitato per permettere accesso diretto al superuser

    # === SUPERUSER SECRET CONFIGURATION ===
    superuserSecret:
      name: ""  # Se vuoto, usa il pattern: {{release-name}}-superuser-credentials
      username: "postgres"  # Username del superuser
      password: ""  # Se vuoto, genera una password casuale

    # Bootstrap configuration
    bootstrap:
      database: prima_nota
      owner: postgres
      secret:
        name: ""  # Se vuoto, usa lo stesso del superuserSecret
      initSql:
        enabled: true
 
    # PostgreSQL parameters
    postgresql:
      parameters:
        max_connections: "200"
        shared_buffers: "256MB"
        effective_cache_size: "1GB"
        work_mem: "4MB"
        maintenance_work_mem: "64MB"
      pg_hba:
        - "local all all trust"
        - "host all all 127.0.0.1/32 md5"
        - "host all all ::1/128 md5"
        - "host all all 0.0.0.0/0 md5"
    
    # Storage configuration
    storage:
      size: 20Gi
      storageClass: ""  # Usa default o specifica (es. ceph-block)
    
    # Resources
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    # Monitoring
    monitoring:
      enabled: true
      customQueriesConfigMap:
        name: ""  # Se vuoto, non usa custom queries
    
    # Backup configuration (opzionale)
    backup:
      enabled: false  # Disabilitato di default
      retentionPolicy: "30d"
      barmanObjectStore:
        destinationPath: ""
        endpointURL: ""
        s3Credentials:
          accessKeyId:
            name: ""
            key: ""
          secretAccessKey:
            name: ""
            key: ""

  # Scheduled Backup (opzionale)
  scheduledBackup:
    enabled: false
    schedule: "0 2 * * *"  # Ogni giorno alle 2:00

# Database Esterno (per casi avanzati)
externalDatabase:
  enabled: false
  host: ""
  port: "5432"
  database: "prima_nota"
  username: "postgres"
  existingSecret: ""
  secretPasswordKey: "password"

backend:
  enabled: true
  image:
    registry: docker.io
    repository: vcnngr/pnbackend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  env:
    NODE_ENV: production
    PORT: 3001
    JWT_SECRET: ""
    RATE_LIMIT_WINDOW_MS: 900000
    RATE_LIMIT_MAX_REQUESTS: 100
    MAX_FILE_SIZE: 10485760
    LOG_LEVEL: info
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /api/health
      port: 3001
    initialDelaySeconds: 50
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3001
    initialDelaySeconds: 30
    periodSeconds: 15

frontend:
  enabled: true
  image:
    registry: docker.io
    repository: vcnngr/pnfrontend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    REACT_APP_API_URL: /api
    REACT_APP_NAME: Prima Nota
    REACT_APP_VERSION: 1.0.0
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

pgadmin:
  enabled: true
  image:
    registry: docker.io
    repository: dpage/pgadmin4
    tag: "9.2"
    pullPolicy: IfNotPresent
  auth:
    email: admin@prima-nota.com
    password: ""
  env:
    PGADMIN_DEFAULT_EMAIL: admin@prima-nota.com
    PGADMIN_DEFAULT_PASSWORD: ""
    PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    PGADMIN_CONFIG_LOGIN_BANNER: "Prima Nota - Database Management"
    PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "20"
    PGADMIN_LISTEN_PORT: "5050"
    PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT: "None"
    PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE: "False"
  service:
    type: ClusterIP
    port: 5050
  resources:
    limits:
      cpu: 700m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /misc/ping
      port: pgadmin
    initialDelaySeconds: 120
    periodSeconds: 60
    timeoutSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /misc/ping
      port: pgadmin
    initialDelaySeconds: 90
    periodSeconds: 45
    timeoutSeconds: 5
    failureThreshold: 3
  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: le-global-issuer
  hosts:
    - host: prima-nota.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /pgadmin
          pathType: Prefix
          service: pgadmin
  tls:
    - secretName: example-tls
      hosts:
        - prima-nota.example.com

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
