# templates/backend-service.yaml
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prima-nota.fullname" . }}-backend
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "prima-nota.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}