# templates/certificate.yaml
{{- if and .Values.tls.enabled .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "prima-nota.fullname" . }}-cert
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
spec:
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuer }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}