{{- if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cloudnativepg.cluster.name | default (printf "%s-postgres" (include "prima-nota.fullname" .)) }}
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudnativepg
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.cloudnativepg.cluster.instances }}
  primaryUpdateStrategy: {{ .Values.cloudnativepg.cluster.primaryUpdateStrategy }}
  
  imageName: {{ .Values.cloudnativepg.cluster.imageName }}
  
  # === SUPERUSER ACCESS ===
  enableSuperuserAccess: {{ .Values.cloudnativepg.cluster.enableSuperuserAccess | default false }}
  
  # === CLUSTER TIMING CONFIGURATION ===
  {{- if .Values.cloudnativepg.cluster.failoverDelay }}
  failoverDelay: {{ .Values.cloudnativepg.cluster.failoverDelay | int }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.startDelay }}
  startDelay: {{ .Values.cloudnativepg.cluster.startDelay | int }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.stopDelay }}
  stopDelay: {{ .Values.cloudnativepg.cluster.stopDelay | int }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.switchoverDelay }}
  switchoverDelay: {{ .Values.cloudnativepg.cluster.switchoverDelay | int }}
  {{- end }}
  
  # === SYNCHRONOUS REPLICATION ===
  {{- if .Values.cloudnativepg.cluster.maxSyncReplicas }}
  maxSyncReplicas: {{ .Values.cloudnativepg.cluster.maxSyncReplicas | int }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.minSyncReplicas }}
  minSyncReplicas: {{ .Values.cloudnativepg.cluster.minSyncReplicas | int }}
  {{- end }}
  
  # === SUPERUSER SECRET ===
  # Usa il secret dedicato per superuser
  superuserSecret:
    name: {{ .Values.cloudnativepg.cluster.superuserSecret.name | default (printf "%s-superuser-credentials" (include "prima-nota.fullname" .)) }}
  
  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepg.cluster.bootstrap.database }}
      owner: {{ .Values.cloudnativepg.cluster.bootstrap.owner }}
      secret:
        # Per bootstrap può usare lo stesso secret del superuser o uno diverso
        name: {{ .Values.cloudnativepg.cluster.bootstrap.secret.name | default (printf "%s-superuser-credentials" (include "prima-nota.fullname" .)) }}
  
  # === POSTGRESQL CONFIGURATION ===
  {{- if .Values.cloudnativepg.cluster.postgresql }}
  postgresql:
    {{- if .Values.cloudnativepg.cluster.postgresql.parameters }}
    parameters:
      {{- toYaml .Values.cloudnativepg.cluster.postgresql.parameters | nindent 6 }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.postgresql.pg_hba }}
    pg_hba:
      {{- toYaml .Values.cloudnativepg.cluster.postgresql.pg_hba | nindent 6 }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.postgresql.shared_preload_libraries }}
    shared_preload_libraries:
      {{- toYaml .Values.cloudnativepg.cluster.postgresql.shared_preload_libraries | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.cloudnativepg.cluster.bootstrap.initSql.enabled }}
  # === VOLUME PER SCRIPT SQL INIT ===
  # Monta il ConfigMap contenente init.sql
  additionalVolumes:
    - name: init-sql-scripts
      configMap:
        name: {{ include "prima-nota.fullname" . }}-config
        items:
        - key: init.sql
          path: init.sql
          mode: 0644
  
  # === MOUNT DEL VOLUME ===
  additionalVolumeMounts:
    - name: init-sql-scripts
      mountPath: /docker-entrypoint-initdb.d
      readOnly: true
  {{- end }}
  
  # === STORAGE CONFIGURATION ===
  storage:
    size: {{ .Values.cloudnativepg.cluster.storage.size }}
    {{- if .Values.cloudnativepg.cluster.storage.storageClass }}
    storageClass: {{ .Values.cloudnativepg.cluster.storage.storageClass }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.storage.resizeInUseVolumes }}
    resizeInUseVolumes: {{ .Values.cloudnativepg.cluster.storage.resizeInUseVolumes }}
    {{- end }}
  
  # === RESOURCES ===
  {{- if .Values.cloudnativepg.cluster.resources }}
  resources:
    {{- toYaml .Values.cloudnativepg.cluster.resources | nindent 4 }}
  {{- end }}
  
  # === AFFINITY AND TOPOLOGY ===
  {{- if .Values.cloudnativepg.cluster.affinity }}
  affinity:
    {{- toYaml .Values.cloudnativepg.cluster.affinity | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.cloudnativepg.cluster.nodeSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudnativepg.cluster.tolerations }}
  tolerations:
    {{- toYaml .Values.cloudnativepg.cluster.tolerations | nindent 4 }}
  {{- end }}
  
  # === MONITORING (Deprecated fields removed) ===
  # Note: monitoring.enabled and podMonitorEnabled are not supported in v1.26.1
  # Monitoring is automatically enabled by CloudNativePG
  
  # === BACKUP CONFIGURATION ===
  {{- if .Values.cloudnativepg.cluster.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.cloudnativepg.cluster.backup.retentionPolicy }}
    barmanObjectStore:
      destinationPath: {{ .Values.cloudnativepg.cluster.backup.destinationPath }}
      {{- if .Values.cloudnativepg.cluster.backup.endpointURL }}
      endpointURL: {{ .Values.cloudnativepg.cluster.backup.endpointURL }}
      {{- end }}
      
      {{- if .Values.cloudnativepg.cluster.env.cloudStorage.enabled }}
      {{- $provider := .Values.cloudnativepg.cluster.env.cloudStorage.provider }}
      
      {{- if eq $provider "aws-s3" }}
      {{- $awsConfig := .Values.cloudnativepg.cluster.env.cloudStorage.awsS3 }}
      {{- if and $awsConfig.credentialsSecret.name $awsConfig.credentialsSecret.accessKeyIdKey $awsConfig.credentialsSecret.secretAccessKeyKey }}
      s3Credentials:
        accessKeyId:
          name: {{ $awsConfig.credentialsSecret.name }}
          key: {{ $awsConfig.credentialsSecret.accessKeyIdKey }}
        secretAccessKey:
          name: {{ $awsConfig.credentialsSecret.name }}
          key: {{ $awsConfig.credentialsSecret.secretAccessKeyKey }}
        {{- if $awsConfig.credentialsSecret.regionKey }}
        region:
          name: {{ $awsConfig.credentialsSecret.name }}
          key: {{ $awsConfig.credentialsSecret.regionKey }}
        {{- end }}
      {{- if $awsConfig.credentialsSecret.endpointUrlKey }}
      endpointURL:
        name: {{ $awsConfig.credentialsSecret.name }}
        key: {{ $awsConfig.credentialsSecret.endpointUrlKey }}
      {{- end }}
      {{- end }}
      
      {{- else if eq $provider "azure-blob-storage" }}
      {{- $azureConfig := .Values.cloudnativepg.cluster.env.cloudStorage.azureBlob }}
      {{- if and $azureConfig.credentialsSecret.name $azureConfig.credentialsSecret.accountNameKey }}
      azureCredentials:
        storageAccount:
          name: {{ $azureConfig.credentialsSecret.name }}
          key: {{ $azureConfig.credentialsSecret.accountNameKey }}
        {{- if $azureConfig.credentialsSecret.accountKeyKey }}
        storageKey:
          name: {{ $azureConfig.credentialsSecret.name }}
          key: {{ $azureConfig.credentialsSecret.accountKeyKey }}
        {{- else if $azureConfig.credentialsSecret.sasTokenKey }}
        storageSasToken:
          name: {{ $azureConfig.credentialsSecret.name }}
          key: {{ $azureConfig.credentialsSecret.sasTokenKey }}
        {{- end }}
      {{- end }}
      
      {{- else if eq $provider "google-cloud-storage" }}
      {{- $gcsConfig := .Values.cloudnativepg.cluster.env.cloudStorage.googleCloud }}
      {{- if and $gcsConfig.credentialsSecret.name $gcsConfig.credentialsSecret.serviceAccountJsonKey }}
      googleCredentials:
        applicationCredentials:
          name: {{ $gcsConfig.credentialsSecret.name }}
          key: {{ $gcsConfig.credentialsSecret.serviceAccountJsonKey }}
        {{- if $gcsConfig.credentialsSecret.projectIdKey }}
        gkeEnvironment: true
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      
      {{- if .Values.cloudnativepg.cluster.backup.wal }}
      wal:
        {{- if .Values.cloudnativepg.cluster.backup.wal.maxParallel }}
        maxParallel: {{ .Values.cloudnativepg.cluster.backup.wal.maxParallel }}
        {{- end }}
        {{- if .Values.cloudnativepg.cluster.backup.wal.compression }}
        compression: {{ .Values.cloudnativepg.cluster.backup.wal.compression }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.cloudnativepg.cluster.backup.data }}
      data:
        {{- if .Values.cloudnativepg.cluster.backup.data.compression }}
        compression: {{ .Values.cloudnativepg.cluster.backup.data.compression }}
        {{- end }}
        {{- if .Values.cloudnativepg.cluster.backup.data.jobs }}
        jobs: {{ .Values.cloudnativepg.cluster.backup.data.jobs }}
        {{- end }}
        {{- if .Values.cloudnativepg.cluster.backup.data.immediateCheckpoint }}
        immediateCheckpoint: {{ .Values.cloudnativepg.cluster.backup.data.immediateCheckpoint }}
        {{- end }}
      {{- end }}
  {{- end }}
  
  # === CERTIFICATES (if needed) ===
  {{- if .Values.cloudnativepg.cluster.certificates }}
  certificates:
    {{- if .Values.cloudnativepg.cluster.certificates.serverTLSSecret }}
    serverTLSSecret: {{ .Values.cloudnativepg.cluster.certificates.serverTLSSecret }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.certificates.serverCASecret }}
    serverCASecret: {{ .Values.cloudnativepg.cluster.certificates.serverCASecret }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.certificates.clientCASecret }}
    clientCASecret: {{ .Values.cloudnativepg.cluster.certificates.clientCASecret }}
    {{- end }}
    {{- if .Values.cloudnativepg.cluster.certificates.replicationTLSSecret }}
    replicationTLSSecret: {{ .Values.cloudnativepg.cluster.certificates.replicationTLSSecret }}
    {{- end }}
  {{- end }}
  
  # === ENVIRONMENT VARIABLES ===
  {{- $envVars := list }}
  
  {{- /* Cloud Storage Provider Configuration */ -}}
  {{- if .Values.cloudnativepg.cluster.env.cloudStorage.enabled }}
    {{- $provider := .Values.cloudnativepg.cluster.env.cloudStorage.provider }}
    
    {{- if eq $provider "aws-s3" }}
      {{- /* AWS S3 / MinIO Configuration */ -}}
      {{- $awsConfig := .Values.cloudnativepg.cluster.env.cloudStorage.awsS3 }}
      {{- if $awsConfig.credentialsSecret.name }}
        {{- /* Secret-based configuration */ -}}
        {{- $envVars = append $envVars (dict 
            "name" "AWS_ACCESS_KEY_ID" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $awsConfig.credentialsSecret.name 
              "key" $awsConfig.credentialsSecret.accessKeyIdKey
            ))
          ) }}
        {{- $envVars = append $envVars (dict 
            "name" "AWS_SECRET_ACCESS_KEY" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $awsConfig.credentialsSecret.name 
              "key" $awsConfig.credentialsSecret.secretAccessKeyKey
            ))
          ) }}
        {{- if $awsConfig.credentialsSecret.regionKey }}
        {{- $envVars = append $envVars (dict 
            "name" "AWS_DEFAULT_REGION" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $awsConfig.credentialsSecret.name 
              "key" $awsConfig.credentialsSecret.regionKey
            ))
          ) }}
        {{- end }}
        {{- if $awsConfig.credentialsSecret.endpointUrlKey }}
        {{- $envVars = append $envVars (dict 
            "name" "AWS_ENDPOINT_URL" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $awsConfig.credentialsSecret.name 
              "key" $awsConfig.credentialsSecret.endpointUrlKey
            ))
          ) }}
        {{- end }}
      {{- else if $awsConfig.direct.accessKeyId }}
        {{- /* Direct configuration */ -}}
        {{- $envVars = append $envVars (dict "name" "AWS_ACCESS_KEY_ID" "value" $awsConfig.direct.accessKeyId) }}
        {{- $envVars = append $envVars (dict "name" "AWS_SECRET_ACCESS_KEY" "value" $awsConfig.direct.secretAccessKey) }}
        {{- if $awsConfig.direct.region }}
        {{- $envVars = append $envVars (dict "name" "AWS_DEFAULT_REGION" "value" $awsConfig.direct.region) }}
        {{- end }}
        {{- if $awsConfig.direct.endpointUrl }}
        {{- $envVars = append $envVars (dict "name" "AWS_ENDPOINT_URL" "value" $awsConfig.direct.endpointUrl) }}
        {{- end }}
      {{- end }}
      
    {{- else if eq $provider "azure-blob-storage" }}
      {{- /* Azure Blob Storage Configuration */ -}}
      {{- $azureConfig := .Values.cloudnativepg.cluster.env.cloudStorage.azureBlob }}
      {{- if $azureConfig.credentialsSecret.name }}
        {{- /* Secret-based configuration */ -}}
        {{- $envVars = append $envVars (dict 
            "name" "AZURE_STORAGE_ACCOUNT" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $azureConfig.credentialsSecret.name 
              "key" $azureConfig.credentialsSecret.accountNameKey
            ))
          ) }}
        {{- if $azureConfig.credentialsSecret.accountKeyKey }}
        {{- $envVars = append $envVars (dict 
            "name" "AZURE_STORAGE_KEY" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $azureConfig.credentialsSecret.name 
              "key" $azureConfig.credentialsSecret.accountKeyKey
            ))
          ) }}
        {{- end }}
        {{- if $azureConfig.credentialsSecret.sasTokenKey }}
        {{- $envVars = append $envVars (dict 
            "name" "AZURE_STORAGE_SAS_TOKEN" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $azureConfig.credentialsSecret.name 
              "key" $azureConfig.credentialsSecret.sasTokenKey
            ))
          ) }}
        {{- end }}
      {{- else if $azureConfig.direct.accountName }}
        {{- /* Direct configuration */ -}}
        {{- $envVars = append $envVars (dict "name" "AZURE_STORAGE_ACCOUNT" "value" $azureConfig.direct.accountName) }}
        {{- if $azureConfig.direct.accountKey }}
        {{- $envVars = append $envVars (dict "name" "AZURE_STORAGE_KEY" "value" $azureConfig.direct.accountKey) }}
        {{- end }}
        {{- if $azureConfig.direct.sasToken }}
        {{- $envVars = append $envVars (dict "name" "AZURE_STORAGE_SAS_TOKEN" "value" $azureConfig.direct.sasToken) }}
        {{- end }}
      {{- end }}
      
    {{- else if eq $provider "google-cloud-storage" }}
      {{- /* Google Cloud Storage Configuration */ -}}
      {{- $gcsConfig := .Values.cloudnativepg.cluster.env.cloudStorage.googleCloud }}
      {{- if $gcsConfig.credentialsSecret.name }}
        {{- /* Secret-based configuration */ -}}
        {{- if $gcsConfig.credentialsSecret.serviceAccountJsonKey }}
        {{- $envVars = append $envVars (dict 
            "name" "GOOGLE_APPLICATION_CREDENTIALS_JSON" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $gcsConfig.credentialsSecret.name 
              "key" $gcsConfig.credentialsSecret.serviceAccountJsonKey
            ))
          ) }}
        {{- end }}
        {{- if $gcsConfig.credentialsSecret.serviceAccountFileKey }}
        {{- $envVars = append $envVars (dict 
            "name" "GOOGLE_APPLICATION_CREDENTIALS" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $gcsConfig.credentialsSecret.name 
              "key" $gcsConfig.credentialsSecret.serviceAccountFileKey
            ))
          ) }}
        {{- end }}
        {{- if $gcsConfig.credentialsSecret.projectIdKey }}
        {{- $envVars = append $envVars (dict 
            "name" "GOOGLE_CLOUD_PROJECT" 
            "valueFrom" (dict "secretKeyRef" (dict 
              "name" $gcsConfig.credentialsSecret.name 
              "key" $gcsConfig.credentialsSecret.projectIdKey
            ))
          ) }}
        {{- end }}
      {{- else if $gcsConfig.direct.serviceAccountJson }}
        {{- /* Direct configuration */ -}}
        {{- $envVars = append $envVars (dict "name" "GOOGLE_APPLICATION_CREDENTIALS_JSON" "value" $gcsConfig.direct.serviceAccountJson) }}
        {{- if $gcsConfig.direct.projectId }}
        {{- $envVars = append $envVars (dict "name" "GOOGLE_CLOUD_PROJECT" "value" $gcsConfig.direct.projectId) }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  
  {{- /* Add any additional custom environment variables */ -}}
  {{- if .Values.cloudnativepg.cluster.env.custom }}
    {{- $envVars = concat $envVars .Values.cloudnativepg.cluster.env.custom }}
  {{- end }}
  
  {{- /* Output environment variables if any */ -}}
  {{- if $envVars }}
  env:
    {{- toYaml $envVars | nindent 4 }}
  {{- end }}
  
  # === SERVICE ACCOUNT ===
  {{- if .Values.cloudnativepg.cluster.serviceAccountTemplate }}
  serviceAccountTemplate:
    {{- toYaml .Values.cloudnativepg.cluster.serviceAccountTemplate | nindent 4 }}
  {{- end }}
  
{{- end }}