{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prima-nota.fullname" . }}-frontend
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: frontend
    port: {{ .Values.frontend.service.port }}
    targetPort: frontend
    protocol: TCP
  selector:
    {{- include "prima-nota.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
