{{- if .Values.ingress.enabled -}}
{{- if .Values.pgadmin.enabled }}
# Middleware Traefik per pgAdmin
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "prima-nota.fullname" . }}-pgadmin-stripprefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - "/pgadmin"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "prima-nota.fullname" . }}-ingress
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.pgadmin.enabled }}
    # Middleware applicato solo al path /pgadmin
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "prima-nota.fullname" . }}-pgadmin-stripprefix@kubernetescrd
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.pgadmin.enabled }}
          # pgAdmin PRIMA (path più specifico)
          - path: /pgadmin
            pathType: Prefix
            backend:
              service:
                name: {{ include "prima-nota.fullname" $ }}-pgadmin
                port:
                  number: {{ $.Values.pgadmin.service.port }}
          {{- end }}
          # Frontend DOPO (path generico)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "prima-nota.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}