# templates/init-user-job.yaml
{{ if .Values.backend.defaultUser.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prima-nota.fullname" . }}-init-user
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: init-user
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "prima-nota.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: init-user
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-backend
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl -f http://{{ include "prima-nota.fullname" . }}-backend:3001/health; do
            echo "Waiting for backend to be ready..."
            sleep 5
          done
      containers:
      - name: create-user
        image: curlimages/curl:latest
        env:
        - name: BACKEND_URL
          value: "http://{{ include "prima-nota.fullname" . }}-backend:3001"
        - name: USERNAME
          value: {{ .Values.backend.defaultUser.username }}
        - name: EMAIL
          value: {{ .Values.backend.defaultUser.email }}
        - name: FIRST_NAME
          value: {{ .Values.backend.defaultUser.firstName }}
        - name: LAST_NAME
          value: {{ .Values.backend.defaultUser.lastName }}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "prima-nota.fullname" . }}-secret
              key: default-user-password
        command:
        - sh
        - -c
        - |
          # Crea l'utente di default tramite API
          curl -X POST "${BACKEND_URL}/api/auth/register" \
            -H "Content-Type: application/json" \
            -d "{
              \"username\": \"${USERNAME}\",
              \"email\": \"${EMAIL}\",
              \"firstName\": \"${FIRST_NAME}\",
              \"lastName\": \"${LAST_NAME}\",
              \"password\": \"${PASSWORD}\"
            }" || echo "User creation failed or user already exists"
{{ end }}