{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prima-nota.fullname" . }}-pgadmin
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prima-nota.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgadmin
  template:
    metadata:
      labels:
        {{- include "prima-nota.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgadmin
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      containers:
      - name: pgadmin
        image: "{{ .Values.pgadmin.image.registry }}/{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
        imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin.auth.email }}
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "prima-nota.fullname" . }}-secret
              key: pgadmin-password
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: {{ .Values.pgadmin.env.PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION | quote }}
        - name: PGADMIN_CONFIG_LOGIN_BANNER
          value: "\"{{ .Values.pgadmin.env.PGADMIN_CONFIG_LOGIN_BANNER }}\""
        - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
          value: {{ .Values.pgadmin.env.PGADMIN_CONFIG_CONSOLE_LOG_LEVEL | quote }}
        - name: PGADMIN_LISTEN_PORT
          value: {{ .Values.pgadmin.env.PGADMIN_LISTEN_PORT | quote }}
        - name: PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT
          value: {{ .Values.pgadmin.env.PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT | quote }}
        - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
          value: {{ .Values.pgadmin.env.PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED | quote }}
        - name: PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE
          value: {{ .Values.pgadmin.env.PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE | quote }}
        - name: SCRIPT_NAME
          value: "/pgadmin"
        ports:
        - name: pgadmin
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin-config
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
          readOnly: true
        livenessProbe:
          httpGet:
            path: /misc/ping
            port: pgadmin
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /misc/ping
            port: pgadmin
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.pgadmin.resources | nindent 10 }}
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: {{ include "prima-nota.fullname" . }}-pgadmin-pvc
      - name: pgadmin-config
        configMap:
          name: {{ include "prima-nota.fullname" . }}-pgadmin-config
{{- end }}
