# templates/pgadmin-deployment.yaml
{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prima-nota.fullname" . }}-pgadmin
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prima-nota.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgadmin
  template:
    metadata:
      labels:
        {{- include "prima-nota.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: "{{ .Values.pgadmin.image.registry }}/{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
        imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin.auth.email }}
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "prima-nota.fullname" . }}-secret
              key: pgadmin-password
        - name: PGADMIN_DISABLE_POSTFIX
          value: "true"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /misc/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /misc/ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.pgadmin.resources | nindent 10 }}
{{- end }}