# templates/pgadmin-service.yaml
{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prima-nota.fullname" . }}-pgadmin
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
  - name: http
    port: {{ .Values.pgadmin.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "prima-nota.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
{{- end }}