{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prima-nota.fullname" . }}-pgadmin-pvc
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  accessModes:
    {{- range .Values.pgadmin.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pgadmin.persistence.size | quote }}
{{- end }}
