# templates/postgresql-service.yaml
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prima-nota.fullname" . }}-postgresql
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    {{- include "prima-nota.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}