apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prima-nota.fullname" . }}-secret
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ if .Values.postgresql.auth.password }}{{ .Values.postgresql.auth.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  jwt-secret: {{ if .Values.backend.env.JWT_SECRET }}{{ .Values.backend.env.JWT_SECRET | b64enc }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  pgadmin-password: {{ if .Values.pgadmin.auth.password }}{{ .Values.pgadmin.auth.password | b64enc }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
  {{- if .Values.backend.defaultUser.enabled }}
  default-user-password: {{ if .Values.backend.defaultUser.password }}{{ .Values.backend.defaultUser.password | b64enc }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
  {{- end }}
