{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "prima-nota.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prima-nota.fullname" . }}-secret
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ if $secret }}{{ index $secret.data "postgres-password" }}{{ else if .Values.postgresql.auth.password }}{{ .Values.postgresql.auth.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  jwt-secret: {{ if $secret }}{{ index $secret.data "jwt-secret" }}{{ else if .Values.backend.env.JWT_SECRET }}{{ .Values.backend.env.JWT_SECRET | b64enc }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{- if .Values.backend.defaultUser.enabled }}
  default-user-password: {{ if $secret }}{{ index $secret.data "default-user-password" }}{{ else if .Values.backend.defaultUser.password }}{{ .Values.backend.defaultUser.password | b64enc }}{{ else }}{{ randAlphaNum 16 | b64enc }}{{ end }}
  {{- end }}
  {{- if .Values.pgadmin.enabled }}
  pgadmin-password: {{ if $secret }}{{ index $secret.data "pgadmin-password" }}{{ else if .Values.pgadmin.auth.password }}{{ .Values.pgadmin.auth.password | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  {{- end }}