{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "prima-nota.fullname" .)) }}
{{- $superuserSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-superuser-credentials" (include "prima-nota.fullname" .)) }}

{{- $postgresPassword := "" }}
{{- if $secret }}
  {{- $postgresPassword = index $secret.data "postgres-password" }}
{{- else if $superuserSecret }}
  {{- $postgresPassword = index $superuserSecret.data "password" }}
{{- else if .Values.cloudnativepg.cluster.superuserSecret.password }}
  {{- $postgresPassword = .Values.cloudnativepg.cluster.superuserSecret.password | b64enc }}
{{- else if .Values.postgresql.auth.password }}
  {{- $postgresPassword = .Values.postgresql.auth.password | b64enc }}
{{- else }}
  {{- $postgresPassword = randAlphaNum 32 | b64enc }}
{{- end }}

# Secret principale per le applicazioni
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prima-nota.fullname" . }}-secret
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ $postgresPassword }}
  jwt-secret: {{ if $secret }}{{ index $secret.data "jwt-secret" }}{{ else if .Values.backend.env.JWT_SECRET }}{{ .Values.backend.env.JWT_SECRET | b64enc }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{- if .Values.pgadmin.enabled }}
  pgadmin-password: {{ if $secret }}{{ index $secret.data "pgadmin-password" }}{{ else if .Values.pgadmin.auth.password }}{{ .Values.pgadmin.auth.password | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  {{- end }}

---
{{- if .Values.cloudnativepg.enabled }}
# SuperUser Secret per CloudNativePG
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepg.cluster.superuserSecret.name | default (printf "%s-superuser-credentials" (include "prima-nota.fullname" .)) }}
  labels:
    {{- include "prima-nota.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudnativepg-superuser
type: kubernetes.io/basic-auth
data:
  username: {{ if $superuserSecret }}{{ index $superuserSecret.data "username" }}{{ else }}{{ .Values.cloudnativepg.cluster.superuserSecret.username | default "postgres" | b64enc }}{{ end }}
  password: {{ $postgresPassword }}
{{- end }}
